### ISSUE TITLE
Bug: llama_index_pq crashing on start

### ISSUE THREAD

**Issue by Razunter** [osi1880vr/prompt_quill#12]
Windows, no docker. Version https://github.com/osi1880vr/prompt_quill/commit/505b596133c205c3fc9de67513b5b6e4b644c8bf
llama_index_pq. Starting with `start_prompt_quill.bat`

Crashing at
```
prompt_quill_ui_qdrant.py 36 <module>
ui = ui_staff()

ui.py 771 __init__
self.civitai_Air = gr.TextArea(self.g.settings_data['civitai_Air'], lines=1, label="Air")

KeyError:
civitai_Air
```

This is an old install, updated to current version.

**Comment by osi1880vr** [comment]
good find, please pull again, it should be fixed.

**Comment by Razunter** [comment]
Yep, works now, thank you.
