### ISSUE TITLE
unclear at best 

### ISSUE THREAD

**Issue by mr-lab** [osi1880vr/prompt_quill#6]
telemetry is enabled by default 
unclear installation instructions 
llama-cpp_windows llama_index_pq llmware_pq , like why so many ... 
i'm willing to convert this to SDWEBUI script , but there is so much unnecessary things 
the second i saw telemetry  working i stopped the installation. 
i understand you want to gather more data but ...  do let us know .

**Comment by osi1880vr** [comment]
What Telemetry you are talking about? I do not receive any data. So let me know what you think is enabled and I will try to turn it off

**Comment by mr-lab** [comment]
> What Telemetry you are talking about? I do not receive any data. So let me know what you think is enabled and I will try to turn it off

![image](https://github.com/osi1880vr/prompt_quill/assets/16530175/739b569e-0a1b-4e12-a8cb-edf894bfb4ea)

**Comment by osi1880vr** [comment]
thats the qdrant server that seems to be sending something if it really does which I don't know, but good hint I will try to find out how to disable that

**Comment by osi1880vr** [comment]
If you dont mind youre welcome in my discord that makes thing much more easy to talk =)

**Comment by XmYx** [comment]
I'm goind to be on the way implement this for comfyui, please if possible, let's aim for using a shared codebase with minor differences that check wether we are in comfy auto or forge, but ultimately we should have a modelloader, qdrant sampler, and llm sampler. with enough modularity, the llm is arbitrary.

**Comment by mr-lab** [comment]
> thats the qdrant server that seems to be sending something if it really does which I don't know, but good hint I will try to find out how to disable that

qdrant that's what making my head spin , i was trying to convert the project to a python script extension for forge and Auto1111 
we need to find a way to make it work ... 
you did some awesome job adding horde and civita    generation , but there is scripts to do that in both auto111 and comfyui 
i will try , thanks again

**Comment by osi1880vr** [comment]
QDRANT__TELEMETRY_DISABLED = true as environment var will disable qdrant telemetry
I add this now to all the scripts to be set by default
https://qdrant.tech/documentation/guides/telemetry/

**Comment by osi1880vr** [comment]
I did disable the telemetry now for haystack and llama-index, llmware will follow as soon as I finished the other updates im doing there

**Comment by osi1880vr** [comment]
Telemetry is taken care for now so its closed
